#!/usr/bin/env python3
"""
Template generation module for pwn pipeline.
Creates exploit templates, GDB scripts, and writeup templates.
"""
import argparse
import shutil
import sys
from pathlib import Path
from typing import Optional

from utils import (
    logger, setup_logging, ensure_directories, get_vault_dir, configure_paths,
    get_script_dir, build_vault_path, check_directory_exists
)


def create_writeup_template(challenge_name: str, vault_path: Path = None,
                           ctf_name: str = None) -> Path:
    """
    Create writeup template in Obsidian vault with substituted placeholders.

    Args:
        challenge_name: Name of the challenge
        vault_path: Base path for vault (defaults to config)
        ctf_name: Optional CTF name for organization

    Returns:
        Path to the created writeup template
    """
    logger.info(f"Creating writeup template for {challenge_name}")

    vault_challenge_path = build_vault_path(challenge_name, ctf_name, vault_path)

    # Check if directory already exists
    check_directory_exists(vault_challenge_path, "Vault directory")

    ensure_directories(vault_challenge_path)

    template_src = get_script_dir() / "templates" / "writeup_template.md"
    template_dst = vault_challenge_path / f"{challenge_name}.md"

    # Read template and substitute placeholders
    with open(template_src, "r") as f:
        content = f.read()

    content = content.replace("{{CTF_NAME}}", challenge_name)

    with open(template_dst, "w") as f:
        f.write(content)

    logger.info(f"Created writeup template: {template_dst}")
    return template_dst


def create_exploit_template(challenge_name: str, binary_path: Path,
                           dest_dir: Path, filename: str = "exploit.py") -> Path:
    """
    Generate a pwntools exploit template.

    Args:
        challenge_name: Name of the challenge
        binary_path: Path to the target binary
        dest_dir: Destination directory
        filename: Name for the exploit file

    Returns:
        Path to the created exploit template
    """
    logger.info(f"Generating pwntools exploit template")

    template_content = f'''#!/usr/bin/env python3
"""
Exploit for {challenge_name}
Generated by pwn-pipeline
"""
from pwn import *

# Set up pwntools for the correct architecture
exe = ELF("./{binary_path.name}")
context.binary = exe
context.log_level = "debug"
context.terminal = ["tmux", "split-window", "-h"]

# Many built-in settings can be controlled on the command-line and show up
# in "args".  For example, to dump all data sent/received, and disable ASLR
# for all created processes...
# ./exploit.py DEBUG NOASLR
# ./exploit.py GDB HOST=example.com PORT=4141 EXE=/tmp/executable
host = args.HOST or "localhost"
port = int(args.PORT or 1337)


def start_local(argv=[], *a, **kw):
    """Execute the target binary locally"""
    if args.GDB:
        return gdb.debug([exe.path] + argv, gdbscript=gdbscript, *a, **kw)
    else:
        return process([exe.path] + argv, *a, **kw)


def start_remote(argv=[], *a, **kw):
    """Connect to the process on the remote host"""
    io = connect(host, port)
    if args.GDB:
        gdb.attach(io, gdbscript=gdbscript)
    return io


def start(argv=[], *a, **kw):
    """Start the exploit against the target"""
    if args.REMOTE:
        return start_remote(argv, *a, **kw)
    else:
        return start_local(argv, *a, **kw)


# Specify GDB script here (breakpoints etc)
gdbscript = """
continue
""".format(**locals())

# ===========================================================
#                    EXPLOIT GOES HERE
# ===========================================================

io = start()

# Example: receive until prompt and send payload
# io.recvuntil(b"Input: ")
# payload = b"A" * 64
# io.sendline(payload)

# Get the flag
io.interactive()

'''

    exploit_path = dest_dir / filename
    logger.debug(f"Writing exploit to: {exploit_path}")
    logger.debug(f"dest_dir={dest_dir}, filename={filename}")

    with open(exploit_path, "w") as f:
        f.write(template_content)

    # Make it executable
    exploit_path.chmod(0o755)
    logger.info(f"Created exploit template: {exploit_path}")
    return exploit_path


def create_gdb_init(binary_path: Path, dest_dir: Path,
                   filename: str = ".gdbinit") -> Path:
    """
    Generate GDB/pwndbg initialization script.

    Args:
        binary_path: Path to the target binary
        dest_dir: Destination directory
        filename: Name for the GDB init file

    Returns:
        Path to the created GDB init script
    """
    logger.info(f"Generating GDB initialization script")

    gdb_content = f'''# GDB Init Script for {binary_path.name}
# Generated by pwn-pipeline
# Load with: gdb -x .gdbinit {binary_path.name}

# Set disassembly flavor
set disassembly-flavor intel

# Disable pagination
set pagination off

# Show context on every step (if using pwndbg/gef)
# context

# Common breakpoints (uncomment as needed)
# break main
# break *main+offset
# break vulnerable_function

# Display useful information
# backtrace
# info frame
# info functions
# info variables

# Heap information (if using pwndbg)
# heap info

# Run with arguments
# set args arg1 arg2

# Start commands
echo \\n[*] GDB initialized for {binary_path.name}\\n
echo [*] Suggested commands:\\n
echo     - info functions\\n
echo     - disass main\\n
echo     - checksec\\n
echo     - vmmap\\n
echo     - search\\n
echo \\n

# Auto-run (uncomment to start automatically)
# run
'''

    gdb_init_path = dest_dir / filename
    with open(gdb_init_path, "w") as f:
        f.write(gdb_content)

    logger.info(f"Created GDB init script: {gdb_init_path}")
    return gdb_init_path


def create_solve_template(dest_dir: Path, filename: str = "solve.sh") -> Path:
    """
    Create a simple bash script template for quick solving.

    Args:
        dest_dir: Destination directory
        filename: Name for the solve script

    Returns:
        Path to the created solve script
    """
    logger.info("Generating solve script template")

    solve_content = '''#!/usr/bin/env bash
# Quick solve script
# Usage: ./solve.sh [local|remote]

MODE=${1:-local}

if [ "$MODE" = "local" ]; then
    echo "[*] Running exploit locally..."
    python3 exploit.py LOCAL
elif [ "$MODE" = "remote" ]; then
    echo "[*] Running exploit remotely..."
    # Update HOST and PORT as needed
    python3 exploit.py HOST=ctf.example.com PORT=1337
else
    echo "Usage: $0 [local|remote]"
    exit 1
fi
'''

    solve_path = dest_dir / filename
    logger.debug(f"Writing solve script to: {solve_path}")
    logger.debug(f"dest_dir={dest_dir}, filename={filename}")

    with open(solve_path, "w") as f:
        f.write(solve_content)

    solve_path.chmod(0o755)
    logger.info(f"Created solve script: {solve_path}")
    return solve_path


def generate_all_templates(challenge_name: str, challenge_dir: Path,
                          binary_path: Optional[Path] = None,
                          vault_path: Path = None, ctf_name: str = None) -> dict:
    """
    Generate all templates for a challenge.

    Args:
        challenge_name: Name of the challenge
        challenge_dir: Challenge directory path
        binary_path: Path to primary binary (optional)
        vault_path: Base vault path (defaults to config)
        ctf_name: Optional CTF name for organization

    Returns:
        Dictionary with paths to all generated templates
    """
    logger.info(f"Generating all templates for {challenge_name}")
    logger.debug(f"challenge_dir parameter: {challenge_dir}")
    logger.debug(f"binary_path parameter: {binary_path}")
    
    if vault_path is None:
        vault_path = get_vault_dir()
        
    logger.debug(f"vault_path parameter: {vault_path}")
    logger.debug(f"ctf_name parameter: {ctf_name}")

    templates = {}

    # Writeup template
    templates["writeup"] = create_writeup_template(challenge_name, vault_path, ctf_name)

    # Binary-specific templates
    if binary_path and binary_path.exists():
        logger.debug(f"Creating binary-specific templates in: {challenge_dir}")
        templates["exploit"] = create_exploit_template(
            challenge_name, binary_path, challenge_dir
        )
        templates["gdb_init"] = create_gdb_init(binary_path, challenge_dir)
        templates["solve"] = create_solve_template(challenge_dir)
    else:
        logger.warning("No binary provided, skipping exploit and GDB templates")

    logger.info(f"Generated {len(templates)} templates")
    return templates


def move_analysis_to_vault(challenge_dir: Path, challenge_name: str,
                           vault_path: Path = None, ctf_name: str = None) -> Optional[Path]:
    """
    Move analysis.md from challenge directory to vault.

    Args:
        challenge_dir: Challenge directory
        challenge_name: Name of the challenge
        vault_path: Base vault path (defaults to config)
        ctf_name: Optional CTF name for organization

    Returns:
        Path to moved analysis file, or None if not found
    """
    vault_challenge_dir = build_vault_path(challenge_name, ctf_name, vault_path)
    ensure_directories(vault_challenge_dir)

    analysis_src = challenge_dir / "analysis.md"
    if analysis_src.exists():
        analysis_dst = vault_challenge_dir / "analysis.md"
        shutil.move(str(analysis_src), str(analysis_dst))
        logger.info(f"Moved analysis to: {analysis_dst}")
        return analysis_dst
    else:
        logger.warning("analysis.md not found, skipping move")
        return None


def main():
    """Main entry point for templates script."""
    parser = argparse.ArgumentParser(
        description="Generate templates for CTF challenge",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--name", required=True, help="CTF challenge name")
    parser.add_argument("-c", "--ctf", help="CTF name for organization")
    parser.add_argument("--challenge-dir", type=Path, required=True,
                       help="Challenge directory path")
    parser.add_argument("--binary", type=Path, help="Path to primary binary")
    parser.add_argument("--vault-path", type=Path,
                       help="Vault base path (defaults to config)")
    parser.add_argument("-v", "--verbose", action="store_true",
                       help="Enable verbose logging")
    parser.add_argument("--debug", action="store_true",
                       help="Enable debug mode (use test paths)")
    args = parser.parse_args()

    setup_logging(args.verbose)
    configure_paths(args.debug)

    try:
        # Generate templates
        templates = generate_all_templates(
            args.name,
            args.challenge_dir,
            args.binary,
            args.vault_path,
            args.ctf
        )

        # Move analysis if exists
        move_analysis_to_vault(args.challenge_dir, args.name, args.vault_path, args.ctf)

        # Print summary
        print(f"\n{'='*60}")
        print(f"Templates Generated: {args.name}")
        print(f"{'='*60}")
        for name, path in templates.items():
            print(f"  - {name}: {path}")
        print(f"{'='*60}\n")

        return 0

    except Exception as e:
        logger.error(f"Template generation failed: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
